// packages/svelte/src/Tinyflow.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import {
        Tinyflow as TinyflowNative,
        type TinyflowOptions
    } from '@tinyflow-ai/ui';
    import '@tinyflow-ai/ui/dist/index.css';

    const { style, className, ...rest }: {
        style?: Record<string, string> | string;
        className?: string;
        // data: TinyflowOptions['data']
    } & Omit<TinyflowOptions, 'element'> = $props();


    // Internal state
    let divRef: HTMLElement | null = null;
    let tinyflowInstance: TinyflowNative | null = null;

    // Expose imperative handle
    export function getData() {
        if (tinyflowInstance) {
            return tinyflowInstance.getData();
        }
        console.warn('Tinyflow instance is not initialized');
        return null;
    }

    // Lifecycle: Mount
    onMount(() => {
        if (divRef) {
            tinyflowInstance = new TinyflowNative({
                ...rest,
                element: divRef
            });

            return () => {
                if (tinyflowInstance) {
                    tinyflowInstance.destroy();
                    tinyflowInstance = null;
                }
            };
        }
    });
    const defaultStyle = { height: '600px' };
    const combinedStyle = { ...defaultStyle, ...style as Record<string, string> };

    function styleObjectToString(styleObj: Record<string, string>): string {
        return Object.entries(styleObj)
            .map(([key, value]) => `${key}: ${value};`)
            .join(' ');
    }

    const combinedStyleString = typeof style === 'string' ? style : styleObjectToString(combinedStyle);
</script>

<div
    bind:this={divRef}
    style={combinedStyleString }
    class={className}
    {...rest}
></div>

// packages/vue/src/Tinyflow.vue
<template>
    <div ref="divRef" :class="['tinyflow', className]" :style="style" />
</template>

<script setup lang="ts">
import { Tinyflow as TinyflowNative, TinyflowOptions } from '@tinyflow-ai/ui';
import '@tinyflow-ai/ui/dist/index.css';
import { onMounted, onUnmounted, ref } from 'vue';

const props = defineProps<
    {
        className?: string;
        style?: Record<string, string>;
    } & Omit<TinyflowOptions, 'element'>
>();

const divRef = ref<HTMLDivElement | null>(null);
let tinyflow: TinyflowNative | null = null;

onMounted(() => {
    if (divRef.value) {
        tinyflow = new TinyflowNative({
            ...props,
            element: divRef.value as Element
        });
    }
});

onUnmounted(() => {
    if (tinyflow) {
        tinyflow.destroy();
        tinyflow = null;
    }
});

const getData = () => {
    if (tinyflow) {
        return tinyflow.getData();
    }
    console.warn('Tinyflow instance is not initialized');
    return null;
};

defineExpose({
    getData
});
</script>
